/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HeaderFooterLayoutRouteImport } from './routes/_headerFooterLayout'
import { Route as HeaderFooterLayoutWidthLimiterLayoutRouteImport } from './routes/_headerFooterLayout/_widthLimiterLayout'
import { Route as HeaderFooterLayoutWidthLimiterLayoutIndexRouteImport } from './routes/_headerFooterLayout/_widthLimiterLayout/index'

const HeaderFooterLayoutRoute = HeaderFooterLayoutRouteImport.update({
  id: '/_headerFooterLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderFooterLayoutWidthLimiterLayoutRoute =
  HeaderFooterLayoutWidthLimiterLayoutRouteImport.update({
    id: '/_widthLimiterLayout',
    getParentRoute: () => HeaderFooterLayoutRoute,
  } as any)
const HeaderFooterLayoutWidthLimiterLayoutIndexRoute =
  HeaderFooterLayoutWidthLimiterLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HeaderFooterLayoutWidthLimiterLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HeaderFooterLayoutWidthLimiterLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof HeaderFooterLayoutWidthLimiterLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_headerFooterLayout': typeof HeaderFooterLayoutRouteWithChildren
  '/_headerFooterLayout/_widthLimiterLayout': typeof HeaderFooterLayoutWidthLimiterLayoutRouteWithChildren
  '/_headerFooterLayout/_widthLimiterLayout/': typeof HeaderFooterLayoutWidthLimiterLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id:
    | '__root__'
    | '/_headerFooterLayout'
    | '/_headerFooterLayout/_widthLimiterLayout'
    | '/_headerFooterLayout/_widthLimiterLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HeaderFooterLayoutRoute: typeof HeaderFooterLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_headerFooterLayout': {
      id: '/_headerFooterLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HeaderFooterLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_headerFooterLayout/_widthLimiterLayout': {
      id: '/_headerFooterLayout/_widthLimiterLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HeaderFooterLayoutWidthLimiterLayoutRouteImport
      parentRoute: typeof HeaderFooterLayoutRoute
    }
    '/_headerFooterLayout/_widthLimiterLayout/': {
      id: '/_headerFooterLayout/_widthLimiterLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HeaderFooterLayoutWidthLimiterLayoutIndexRouteImport
      parentRoute: typeof HeaderFooterLayoutWidthLimiterLayoutRoute
    }
  }
}

interface HeaderFooterLayoutWidthLimiterLayoutRouteChildren {
  HeaderFooterLayoutWidthLimiterLayoutIndexRoute: typeof HeaderFooterLayoutWidthLimiterLayoutIndexRoute
}

const HeaderFooterLayoutWidthLimiterLayoutRouteChildren: HeaderFooterLayoutWidthLimiterLayoutRouteChildren =
  {
    HeaderFooterLayoutWidthLimiterLayoutIndexRoute:
      HeaderFooterLayoutWidthLimiterLayoutIndexRoute,
  }

const HeaderFooterLayoutWidthLimiterLayoutRouteWithChildren =
  HeaderFooterLayoutWidthLimiterLayoutRoute._addFileChildren(
    HeaderFooterLayoutWidthLimiterLayoutRouteChildren,
  )

interface HeaderFooterLayoutRouteChildren {
  HeaderFooterLayoutWidthLimiterLayoutRoute: typeof HeaderFooterLayoutWidthLimiterLayoutRouteWithChildren
}

const HeaderFooterLayoutRouteChildren: HeaderFooterLayoutRouteChildren = {
  HeaderFooterLayoutWidthLimiterLayoutRoute:
    HeaderFooterLayoutWidthLimiterLayoutRouteWithChildren,
}

const HeaderFooterLayoutRouteWithChildren =
  HeaderFooterLayoutRoute._addFileChildren(HeaderFooterLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HeaderFooterLayoutRoute: HeaderFooterLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
